### ISSUE TITLE
Authorizing application

### ISSUE THREAD

**Issue by Bharath-kashyap** [Sage/sageone_api_java_sample#13]
![image](https://cloud.githubusercontent.com/assets/24728817/23850419/64b66ad4-0805-11e7-9413-44e235727833.png)

I am getting this error when i try to generate authorization code for regions CA,UK,DE,FR.
What do i do?

**Comment by Pete-Brown** [comment]
Can you ensure you have the client_id and callback_uri correct.

They need to match exactly what you have registered on https://developers.sageone.com/applications

**Comment by Bharath-kashyap** [comment]
Thank you @Pete-Brown for your help.
