### ISSUE TITLE
Signature invalid error

### ISSUE THREAD

**Issue by Bharath-kashyap** [Sage/sageone_api_java_sample#14]
I am using the signature generation code provided by you and the signature base string being generated is the same as given in the example. But i am getting invalid signature error when a call is made. 

What are reasons for this to happen?

The signature being generated even for a get call(no parameters or request body)  is not working.

The signatureBaseString is : GET&https%3A%2F%2Fapi.columbus.sage.com%2Fus%2Fsageone%2Faccounts%2Fv3%2Fbank_accounts&&t6657d14f6d3d9de478ff4b0dc686abc&6631f7f7d4734a89a357fbc7b3c93191

The code that i am using to generate signature is:

public static void main(String[] args) throws IllegalStateException, UnsupportedEncodingException
	{
		try {
			String result = Base64.getEncoder().encodeToString(hmacSha1());
			System.out.println("result: " +result);
			
		} catch (NoSuchAlgorithmException | InvalidKeyException ex) {
			ex.printStackTrace();
		}
	}
	
	
	private static byte[] hmacSha1() throws NoSuchAlgorithmException, InvalidKeyException, IllegalStateException, UnsupportedEncodingException  {
		final String type = "HmacSHA1";
		final SecretKeySpec secret = new SecretKeySpec(signingKey().getBytes(), type);
		final Mac mac = Mac.getInstance(type);
		mac.init(secret);
		return mac.doFinal(signatureBaseString().getBytes());
		}
	
	
		
	private static String signatureBaseString() throws UnsupportedEncodingException {
		
		//********
		String method="GET";
		String nonce="xxxxxx";
		String guid="xxxxx";
		//*******
		
		String signatureBaseString = "";
		signatureBaseString += method.toUpperCase();
		signatureBaseString += "&";
		signatureBaseString += percentEncode(baseUrl());
		signatureBaseString += "&";
		signatureBaseString += percentEncode(parameterString());
		signatureBaseString += "&";
		signatureBaseString += percentEncode(nonce);
		signatureBaseString += "&";
		signatureBaseString += percentEncode(guid);
		System.out.println("SigBaseStr: " +signatureBaseString);
		return signatureBaseString;
		}
		
		
		private static String signingKey() throws UnsupportedEncodingException {
		//*********
		String secret="xxxxx";
		String token="xxxxx"; 
		//********
		String encodedSigningSecret = percentEncode(secret);
		String encodedAccessToken = percentEncode(token);
		return String.format("%s&%s", encodedSigningSecret, encodedAccessToken);
		}
		
		private static String baseUrl() {
		URL parsedUrl = parsedUrl();
		final String baseUrl = parsedUrl.getProtocol() + "://"
				+ parsedUrl.getAuthority()
				+ parsedUrl.getPath();
		return baseUrl;
		}
		
		private static String parameterString() throws UnsupportedEncodingException {
		//****
		String parameterString = "";
		//****
		TreeMap<String, String> combinedParams = new TreeMap<String,String>();
		combinedParams.putAll(encodedQueryParams());
		combinedParams.putAll(encodedBodyParams());
		
		for (Map.Entry<String, String> entry : combinedParams.entrySet())
		{
			parameterString += entry.getKey();
			parameterString += "=";
			parameterString += entry.getValue();
			parameterString += "&";
		}
		if (parameterString.length() > 0) {
			parameterString = parameterString.substring(0,parameterString.length()-1);
		}
		return parameterString;
		}
		
	private static TreeMap<String, String> encodedQueryParams() throws UnsupportedEncodingException {
		TreeMap<String, String> encodedQueryParams = new TreeMap<String, String>();
		if (parsedUrl().getQuery() != null) {
			String[] queryParams = parsedUrl().getQuery().split("&");
		
			for( int i = 0; i < queryParams.length; i++)
			{
				String[] param = queryParams[i].split("=");
				encodedQueryParams.put(percentEncode(param[0]), percentEncode(param[1]));
			}
		}
		return encodedQueryParams;
		}
		
	
	
	private static TreeMap<String, String> encodedBodyParams() throws         UnsupportedEncodingException {
	
		TreeMap<String, String> encodedBodyParams = new TreeMap<String, String>();
		
		String params = "";
		if(params!="")
			{encodedBodyParams.put("body", params);}
		return encodedBodyParams;
		}
	        private static URL parsedUrl() {
		//****
		String url="https://api.columbus.sage.com/us/sageone/accounts/v3/bank_account_types";
		//****
		
		URL parsedUrl = null;
		try {
			parsedUrl = new URL(url);
		} catch(MalformedURLException ex) {
			ex.printStackTrace();
		}
		return parsedUrl;
		}
	private static String percentEncode(final String string) throws UnsupportedEncodingException {
			String encoded=null;
			string.replaceAll("\\+", "%20");
			encoded = URLEncoder.encode(string, "ISO-8859-1");
			return encoded;
		}

**Comment by buzz1710** [comment]
the signature base string doesn't look right here. If there are no body params, your parameter string should be `body=` so I would expect your signature base string to include `&body%3D&` but your example shows `&&`. Did you base this on the v3 branch?

**Comment by Bharath-kashyap** [comment]
Thank you. I was including "body=" only when the body contained any value. 
It is working now.
