### ISSUE TITLE
Error when creating a sales invoice: tax_address_region_id is required

### ISSUE THREAD

**Issue by mikeshogo** [Sage/sageone_api_java_sample#18]
I'm getting this error when trying to create a sales invoice for a CA company. Is there a deficient setting in the Sage One company, or do we need to supply this value in our API request?

**Comment by timlapluie** [comment]
Hi @retailintel, thanks for using the API and thanks for your question!

In Canada, it is needed that you provide a `tax_address_region_id` in your request when creating a sales invoice. The following regions are currently allowed (according to our documentation: https://developer.columbus.sage.com/docs#/ca/sageone/accounts/v3/sales_invoices_sales_invoice):

`CA-AB`, `CA-BC`, `CA-MB`, `CA-NB`, `CA-NL`, `CA-NS`, `CA-NT`, `CA-NU`, `CA-ON`, `CA-PE`, `CA-QC`, `CA-SK`, `CA-YT`

**Comment by mikeshogo** [comment]
OK- can you please update the docs to specify which fields are required please?

**Comment by timlapluie** [comment]
We will try to update the documentation for that. 
Please note, that this field is only required for a CA business and not used in any other region of Sage One.
