### ISSUE TITLE
API breaking the contracts (changing JSON files)

### ISSUE THREAD

**Issue by wbsouza** [Sage/sageone_api_java_sample#19]
Hello Sage Support,

I started to develop one application and integrate with SageOne (Accountant) Canadian Version, API v3. I also made a contribution, providing better information in your demo application, adjusting configurations, making it more extensible and made a pull request more than one month and until now I didn't get any answer.

The initiative to provide an API is amazing, now we can integrate with Sage in a clean way, but we need a stable API to do it, otherwise, no one wants to spend efforts to integrate with SageOne to be broked later.

Here are the JSON files before and currently running on SageOne integration servers.
[contacts.tar.gz](https://github.com/Sage/sageone_api_java_sample/files/1374118/contacts.tar.gz)

Thanks,

Wellington

**Comment by timlapluie** [comment]
Hi @wbsouza,

I looked into your attached JSON files and can't see any difference at all. Could you please point me to the difference that breaks the API responses for you? Thanks a lot.

**Comment by wbsouza** [comment]
Hi Tim, thanks for your quick answer, I appreciate it :-)
My bad, I made a mistake via command-line to create the file .tar.gz

The change as I said was positive in this scenario but IMHO as an API I this kind of change should not happen in a production environment.

There is a difference if you check right now the JSON comming is:
```
{
   "$items":[
      {
         "displayed_as":"Royal Bank",
         "$path":"/contacts/fdbfb587a7f411e79fb00ed51759bcc7",
         "id":"fdbfb587a7f411e79fb00ed51759bcc7"
      },
      {
         "displayed_as":"World Stone Inc",
         "$path":"/contacts/24b02561a83711e79fb00ed51759bcc7",
         "id":"24b02561a83711e79fb00ed51759bcc7"
      },
      {
         "displayed_as":"Big Tree Construction",
         "$path":"/contacts/e2415407a8c411e79fb00ed51759bcc7",
         "id":"e2415407a8c411e79fb00ed51759bcc7"
      },
      {
         "displayed_as":"World Stone Inc",
         "$path":"/contacts/41ff7cedace611e79fb00ed51759bcc7",
         "id":"41ff7cedace611e79fb00ed51759bcc7"
      }
   ],
   "$back":null,
   "$total":4,
   "$itemsPerPage":50,
   "$next":null,
   "$page":1
}
  
```

and before was:
```
{
  "map": {
    "$items": {
      "myArrayList": [
        {
          "map": {
            "displayed_as": "MGSquare Inc",
            "$path": "/contacts/62f3ed32a02211e79fb00ed51759bcc7",
            "id": "62f3ed32a02211e79fb00ed51759bcc7"
          }
        },
        {
          "map": {
            "displayed_as": "Royal Bank",
            "$path": "/contacts/fdbfb587a7f411e79fb00ed51759bcc7",
            "id": "fdbfb587a7f411e79fb00ed51759bcc7"
          }
        },
        {
          "map": {
            "displayed_as": "MatricStream",
            "$path": "/contacts/24b02561a83711e79fb00ed51759bcc7",
            "id": "24b02561a83711e79fb00ed51759bcc7"
          }
        },
        {
          "map": {
            "displayed_as": "Big Tree Construction",
            "$path": "/contacts/e2415407a8c411e79fb00ed51759bcc7",
            "id": "e2415407a8c411e79fb00ed51759bcc7"
          }
        }
      ]
    },
    "$back": {},
    "$total": 4,
    "$itemsPerPage": 200,
    "$next": {},
    "$page": 1
  }
}
```
If you have a chance, take a look in my logs in your backend sytem, if you need any extra information you can contact me in private and I will provide it.

**Comment by timlapluie** [comment]
OK, so you are talking about the values of `$back` and `$next`, is that correct?

The JSON you posted here is not the original response from the API but an already parsed and slightly changed object.

We haven't ever returned `{}` as `null` values for `$next` and `$back` in the past. Maybe something changed in the implementation of the `map` function in the code or even in the JSON parser that is used for that. It is definitely no breaking change in the API. When no `$next`/`$back` link is available, the API always returns `null`.

**Comment by wbsouza** [comment]
No, have look into the first JSON (current implementation) above, to get the ID of the first element you have to do:
```
...
json = callCustomerEndpoint( );
console.log( json.$items[0].id );
...
```

The second JSON (previous implementation) to get the ID of the first element you have to do:
```
...
json = callCustomerEndpoint( );
console.log( json.map.$items.myArrayList[0].id );
...
```
Apparently, it was a "bug" because was exposing some implementation details like "map" and "myArrayList". Anyway, I am happy with the current version (I already have changed all my implementations for the current format), it seems more fluent and concise, but because the v3 is still in beta no one is really using yet.

**Comment by timlapluie** [comment]
API `v3` never returned a JSON object with your given "old" structure. As I mentioned earlier, I assume that the mapping inside the Java client changed somehow. You can be sure that the API v3 will always return data with the structure you get today. Because it is a public API, there won't be breaking changes in the API responses (which always would need a new API version).

I propose that this issue can then be closed.

**Comment by wbsouza** [comment]
I don't know if you have access to the production environment, but I guess in some hell someone is able to recover the exchanged messages to confirm what I am talking about.  I'm working with a team, at least two more developers can tell you this. I went to sleep passing all my test cases and on the next day suddenly all my automated test cases with sageone were broken, so I found the JSON was changed.

I'm not complaining about the current format, as I said, I think it's better and I already fixed it and I'm happy with the current state of the API. So I'm going to close this issue because there is no point on it.

Thanks again for your support

**Comment by wbsouza** [comment]
Hi @timlapluie, you were right. This error was because I was passing directly an instance of org.json.JSONObject to com.google.gson.Gson to get a formatted JSON. Impressively, it tricks everyone after I remove the indentation to make the package more compressed. The trick to getting the JSON indented in Java is to convert the JSON into a Map and after you can pass to Gson. Bellow is the code who may are using Java.
```
        String jsonContent = ... // calling the SageOne API

        // getting a formatted json (optional) ...
        final Gson gson = new GsonBuilder().setPrettyPrinting().create();
        final Type typeOfMap = new TypeToken<Map<String, Object>>() {}.getType();
        final Map<String, String> map = gson.fromJson(jsonContent, typeOfMap);
        final String formattedJson = gson.toJson(map);
        System.out.println(formattedJson);
```

**Comment by timlapluie** [comment]
Thanks for your response and also thanks for providing a way how you solved the issue 👍
