### ISSUE TITLE
JSON Contact does not bring all the addresses and person_contacts associated

### ISSUE THREAD

**Issue by wbsouza** [Sage/sageone_api_java_sample#20]
Let's say if we have a Customer with many branches in the city (A bank for example), we should be able to recover all the contacts associated with each branch. Currently, we are able to get just the main_address and the first delivery_address. We should be able to recover an array of addresses and person_contact associated to a specific contact.

**Comment by wbsouza** [comment]
Here is one example of a customer with 4 different addresses with contact_persons associated and we don't have a way to get this information through the API.
[customer.tar.gz](https://github.com/Sage/sageone_api_java_sample/files/1374466/customer.tar.gz)

**Comment by timlapluie** [comment]
Hi @wbsouza, you can add a query parameter to any GET request of `/addresses` to specify a specific contact. The URL then should look like this:
`/addresses?contact_id=e38a3033af1711e7bb3b065b8ec10ed1`
Then you have all addresses of a `contact`. You can then get all associated `contact_persons` of an address by adding an `address_id` to the GET query to `contact_persons`:
`/contact_persons?address_id=ece67ebcaf1711e7bb3b065b8ec10ed1`

With that, you can request all `contact_persons` for all `addresses` of a `contact`.

**Comment by wbsouza** [comment]
Ohhh, awesome! I did not see that parameters, it definitely solve the problem.
Thank you very much
