### ISSUE TITLE
URL "View and pay this invoice"

### ISSUE THREAD

**Issue by wbsouza** [Sage/sageone_api_java_sample#23]
Hi All, I'm creating a task to send an email as a reminder to customers who has outstanding invoices. I would like to know if there is any way to get through the API the link "View and pay this invoice" that SageOne send by email.

**Comment by timlapluie** [comment]
Hi @wbsouza,

I'm sorry, but this URL you are looking for is not available.

**Comment by wbsouza** [comment]
Thanks for your anser
