### ISSUE TITLE
Invoice Payment

### ISSUE THREAD

**Issue by wbsouza** [Sage/sageone_api_java_sample#24]
I would like to proceed the payment of a sales invoice through the API.
Accordingly, to the [version 1 to create an invoice payment](https://developer.sageone.com/docs/en/v1#sales_invoices-create_a_payment) is straightforward.

But with the [version 3](https://developer.columbus.sage.com/docs#/ca/sageone/accounts/v3/sales_invoices) to create an invoice payment is not clear which endpoint I have to call and which values should I provide.

Is there any other source of information using the version 3 or a code sample (can be any language) how to proceed it?

By the way, I'm using the Canadian Version

**Comment by timlapluie** [comment]
Hi @wbsouza,

to create a `payment` for an invoice, you'll need to POST a `contact_payment` to the `/contact_payments` endpoint. See https://developer.columbus.sage.com/docs#/ca/sageone/accounts/v3/contact_payments_contact_payment for a list of all attributes you can use for that.

Please be sure to have 
```
allocated_artefacts: [
  {
    artefact_id: <YOUR ARTEFACT ID>,
    amount: <YOUR AMOUNT>,
    discount: <YOUR DISCOUNT>
  }
]
```
in your post data.

**Comment by wbsouza** [comment]
Yeap, again it's working 👍
