### ISSUE TITLE
HTTP status 404 deleting invoice

### ISSUE THREAD

**Issue by wbsouza** [Sage/sageone_api_java_sample#25]
Right after creating an invoice, I'm trying to delete it and I'm getting a 404 error status from the SageOne API server. Find attached the JSON body's message.
[invoice-created.json.tar.gz](https://github.com/Sage/sageone_api_java_sample/files/1498248/invoice-created.json.tar.gz)

for the request Submission:
- method=DELETE
- endpoint=/accounts/v3/sales_invoices/9935dd93d00a11e79fb00ed51759bcc7

Messages: * Unable to match incoming request to an operation.

**Comment by cpetschnig** [comment]
When you delete an invoice, it's actually voided and an reverting transaction is added to your books. You always have to provide a `void_reason` when doing so: `DELETE /accounts/v3/sales_invoices/9935dd93d00a11e79fb00ed51759bcc7?void_reason=The%20customer%20went%20bankrupt`. Does this work for you?

I fully agree the error message is very misleading. We are working on improving such issues.

**Comment by wbsouza** [comment]
Hi @cpetschnig , Thanks for this trick, it's working now.
