### ISSUE TITLE
Tax amount is not calculated

### ISSUE THREAD

**Issue by RemiBou** [Sage/sageone_api_java_sample#31]
Hi

When I post the following invoice 

`{
   "sales_invoice":{
      "contact_id":"6606ca878ffa44808da87fc27ffac171",
      "date":"2019-02-26",
      "invoice_lines":[
         {
            "description":"Eye light",
            "ledger_account_id":"3218fa1f5b414d79bd6195c7f0fd45b2",
            "quantity":1.0,
            "tax_rate_id":"FR_STANDARD",
            "unit_price":10.0,
            "unit_price_includes_tax":true
         },
         {
            "description":"Telephon",
            "ledger_account_id":"0746cc9b2cc84f08b951fa2ff196c51f",
            "quantity":1.0,
            "tax_rate_id":"FR_LOWER_1",
            "unit_price":12.0,
            "unit_price_includes_tax":true
         }
      ],
      "main_address":{
         "address_line_1":"bla bla",
         "address_type_id":"ACCOUNTS",
         "city":"Toulouse",
         "country_code":"FR",
         "postal_code":"31000"
      },
      "reference":"TEST_123",
      "status_id":"DRAFT"
   }
}`

The invoice is created in sage cloud but the VAT Amount column is 0. How can I let sage compute the VAT amount ?

**Comment by cpetschnig** [comment]
Hi Rémi, unfortunately you have to calculate the tax by yourself. Apologies for this inconvenience.

**Comment by RemiBou** [comment]
Ok, can you update the documentation here https://developer.sage.com/api/accounting/guides/invoicing/ ?

**Comment by cpetschnig** [comment]
The documentation now says:

> Your application has to calculate the tax amount (if there is no other source, ie. on purchase invoices) and send in a value, otherwise the tax amount will be set to zero. To calculate the tax amount, you will need the percentage value of the tax rate for the line item. The formula then is
> 
>     tax_amount = net_amount * tax_percentage / 100
> 
> 

Thank you for reporting this!
