### ISSUE TITLE
Formato do valor data para post

### ISSUE THREAD

**Issue by javacunha** [Sage/sageone_api_java_sample#7]
Ao usar o método abaixo da classe SageoneData.
protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException

Ele recebe como um dos parametros o campo data.
String jsonBody = req.getParameter("data");

Qual deve ser ser formato? Ou seja o que deve conter e a forma no campo data.

Por exemplo se eu estiver enviando um objeto do tipo Contacts.

**Comment by adamgeorgeson** [comment]
Hi,

The content type is `application/x-www-form-urlencoded`.

An example for contacts is provided

```
{'contact[contact_type_id]': 1, 'contact[name]': 'Joe Bloggs'}
```

Let us know if there are further issues.

Thanks for getting in touch!
Adam.

**Comment by javacunha** [comment]
Ok. Funcionou em parte.

Recebi o seguinte erro agora:

Envio:
{'contact[id]':0, 'contact[contact_type_id]':1, 'contact[name]':'André Cunha', 'contact[company_name]':'Veweb', 'contact[name_and_company_name]':'null', 'contact[email]':'null', 'contact[telephone]':'null', 'contact[mobile]':'null', 'contact[notes]':'null', 'contact[tax_reference]':'null'}

Resposta.
resp: {
  "map": {
    "$diagnoses": {
      "myArrayList": [
        {
          "map": {
            "$dataCode": "AuthorizationFailure",
            "$message": "Access Denied",
            "$severity": "error",
            "$source": ""
          }
        }
      ]
    }
  }
}

Outra pergunta: Algum método que transforme o objeto neste padrão de json de vcs?
